#This is the version of the Docker Compose file format.
version: '3'


services:
        web:
                build: .
                ports:
                        -"8080:80"
                volumes:
                        -.:/usr/local/apache2/htdocs/
